# Generated by Django 5.2.8 on 2025-11-28 10:01

import django.db.models.deletion
import offers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to=offers.models.cv_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('dubai_lassi_home', 'DUBAI - LASSI HOME SHOP'), ('rak_hamrah', 'RAK - LEPTIS SHOPPING CENTER AL HAMRAH'), ('rak_marjan', 'RAK - LEPTIS SUPERMARKET MARJAN'), ('alain_spicy', 'AL AIN - SPICY VILLAGE AL AIN'), ('alain_leptis', 'AL AIN - LEPTIS SHOPPING CENTER AL AIN')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='offers/pdfs/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='offers/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='offers.offer')),
            ],
        ),
    ]
